spring:
  application:
    name: liquibase
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}

server:
  port: 8081
  servlet:
    context-path: /liquibase